### PR TITLE
Allow the usage of AWS profiles

### PR DESCRIPTION
**Pull request by fiunchinho**

### CODE REVIEW

**Comment by fiunchinho** [comment]
@snakelab is this what you wanted? Could you test this branch?

**Comment by snakelab** [comment]
@fiunchinho thanks, i will test it these days and report....

**Comment by fiunchinho** [comment]
Let me know if this works as expected please

**Comment by snakelab** [comment]
i got it not working at the moment i get this error:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "bucket": "grld-unknown",
            "ec2_url": null,
            "elasticsearch_host": "search-es-dev-unknown.eu-central-1.es.amazonaws.com",
            "host": "search-es-dev-unknown.eu-central-1.es.amazonaws.com",
            "profile": "daily",
            "region": "eu-central-1",
            "repository_name": "s3snapshots",
            "role_arn": "arn:aws:iam::unknown:role/backup_unknown",
            "security_token": null,
            "snapshot_name": null,
            "validate_certs": true
        },
        "module_name": "aws_elasticsearch_snapshot"
    },
    "msg": "BotoServerError: 500 Server Error\n{\"error\":{\"root_cause\":[{\"type\":\"repository_exception\",\"reason\":\"[s3snapshots] failed to create repository\"}],\"type\":\"repository_exception\",\"reason\":\"[s3snapshots] failed to create repository\",\"caused_by\":{\"type\":\"amazon_client_exception\",\"reason\":\"Unable to load AWS credentials from any provider in the chain\"}},\"status\":500}"
}
```
That is the call in my playbook:

```
  - name: "=>{{ deploy_config[domain.name]['current'].domain  | upper }}: Registering Snapshopt Repository in ElasticSearch"
    aws_elasticsearch_snapshot:
      profile: "daily"
      region: "{{ domain.region }}"
      elasticsearch_host: "{{ deploy_config[domain.name]['current'].endpoint }}"
      role_arn: "arn:aws:iam::{{ aws_account_id }}:role/{{ domain.backup.s3.role }}"
      bucket: "grld-unknown"
      repository_name: "s3snapshots"
```

This is my .aws/credentials

```
[daily]
aws_access_key_id = XXXXXXXXXXXXXXXXX
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

On console i get the expected answer regarding s3:

`AWS_PROFILE=daily aws s3 ls grld-unknown --region eu-central-1`

I am still searching the cause...

Hartmut

**Comment by fiunchinho** [comment]
I just tried and it did work fine

**Comment by snakelab** [comment]
Error was on my side: My role policy had an typo, so i got no access to the s3.
It is all working like a charm!
Thanks for adding this feature!
Hartmut

**Comment by fiunchinho** [comment]
You are welcome @snakelab. Thanks for testing!

**Pull request merged**
